"calibre-gui" = ""
"chromium" = ""
"code-oss" = ""
"discord" = ""
"dmenu" = ""
"dmenu-browser" = ""
"dmenu-clipboard" = ""
"dmenu-emoji" = ""
"dmenu-pass" = ""
"dmenu-pass generator" = ""
"draw.io" = ""
"firefox" = ""
"kitty" = ""
"krita" = ""
"libreoffice-calc" = ""
"libreoffice-writer" = ""
"mpv" = ""
"nemo" = ""
"neomutt" = ""
"org.pwmt.zathura" = ""
"org.qutebrowser.qutebrowser" = ""
"paperwork" = ""
"pavucontrol" = ""
"peek" = ""
"qalculate-gtk" = ""
"qutepreview" = ""
"scli" = ""
"swappy" = ""
"transmission-gtk" = ""
"vimiv" = ""
"virt-manager" = ""
"xplr" = ""

"DEFAULT" = ""
