version: v0.5.1

general:
  focus_ui:
    style:
      fg: Cyan

node_types:
  directory:
    meta:
      icon: ""
    style:
      fg: Blue
  file:
    meta:
      icon: ""
    style:
      add_modifier:
        bits: 2
  symlink:
    meta:
      icon: ""
    style:
      add_modifier:
        bits: 0

modes:
  builtin:
    default:
      key_bindings:
        on_key:
          e:
            help: editor
            messages:
              - BashExec: '${EDITOR:-vi} "${XPLR_FOCUS_PATH:?}"'
          D:
            help: disk usage
            messages:
              - BashExec: ncdu
              - ClearScreen
