---
outputMode: active
scale: 2
background:
  red: 0.14
  green: 0.14
  blue: 0.14
  opacity: 1
widget:
  margin:
    margins: [40, 40, 40, 40]
    widget:
      verticalLayout:
        - horizontalLayout:
            - margin:
                margins: [0, 176, 0, 64]
                widget:
                  verticalLayout:
                    - date:
                        font: ~
                        font_size: 128.0
                    - clock:
                        font: ~
                        font_size: 512.0
            - verticalLayout:
                - margin:
                    margins: [0, 0, 0, 16]
                    widget:
                      battery:
                        font: ~
                        font_size: 48.0
                        length: 0
        - calendar:
            font_primary: ~
            font_secondary: ~
            font_size: 32.0
            sections: 3
        - launcher:
            font: ~
            font_size: 64.0
            length: 0
            app_opener: "cglaunch"
            term_opener: "cglaunch --term"
            url_opener: ""

fonts:
  sans: sans
  mono: mono
