theme = "gruvbox_community"

[editor]
color-modes = true
auto-save = true
cursorline = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
ignore = false

[editor.indent-guides]
character = "┊"
render = true
skip-levels = 1

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.search]
smart-case = false

[editor.statusline]
left = ["mode", "file-name", "spinner", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "file-type", "file-line-ending", "position"]
mode.normal = ""
mode.insert = "I"
mode.select = "S"

[keys.normal]
H = "extend_char_left"
J = ["extend_line_down", "extend_to_line_bounds"]
K = ["extend_line_up", "extend_to_line_bounds"]
L = "extend_char_right"
B = "extend_prev_word_start"
W = "extend_next_word_start"
E = "extend_next_word_end"
T = "extend_till_char"
F = "extend_next_char"
A-t = "till_prev_char"
A-f = "find_prev_char"
A-T = "extend_till_prev_char"
A-F = "extend_prev_char"
A-j = "join_selections"
A-k = "keep_selections"
M = ["select_mode", "match_brackets", "normal_mode" ]
"#" = "toggle_comments"
A-l = "extend_to_line_end"
A-h = "extend_to_line_start"
left = "goto_previous_buffer"
right = "goto_next_buffer"
A-d = "delete_selection"
c = "change_selection_noyank"
d = "delete_selection_noyank"
N = "extend_search_next"
A-n = "search_prev"
A-N = "extend_search_prev"
C-d = ["page_cursor_half_down", "align_view_center"]
C-u = ["page_cursor_half_up", "align_view_center"]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

[keys.normal.g]
j = "goto_last_line"
k = "goto_file_start"

[keys.normal.space]
c = ":buffer-close"
"." = ":toggle auto-format"
q = ":write-quit-all"
Q = ":quit!"
e = ":config-open"
w = ":write"
A-f = ":toggle file-picker.git-ignore"

[keys.insert]
C-d = ["page_cursor_half_down", "align_view_center"]
C-u = ["page_cursor_half_up", "align_view_center"]
C-space = "completion"
S-tab = "move_parent_node_start"

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
